name: Continuous builds

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
  
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest, macos-latest,  macos-11 ]
        engine: [ jNeuroML, jNeuroML_NEURON, jNeuroML_EDEN, jNeuroML_validate, "EDEN:0.2.0", "EDEN:0.2.2", "EDEN:0.2.3" ]
        python-version: [ 3.9 ]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version:  ${{ matrix.python-version }}
        
    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        
    - name: Run OMV tests on engine ${{ matrix.engine }}
      run: |
        omv all -V --engine=${{ matrix.engine }}
        
        
    - name: Print final OMV/engine version info
      run: |
        omv list -V # list installed engines
        pip list
