name: Continuous builds

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
  
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.9 ]
        runs-on: [ ubuntu-latest, macos-latest ]
        engine: [ jNeuroML, jNeuroML_NEURON, jNeuroML_EDEN, jNeuroML_validate, EDEN, "EDEN:0.2.0" ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}
        
    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        
    - name: Install EDEN
      run: |
        pip install eden-simulator
        omv list -V # list installed engines
        
    - name: Run EDEN examples directly
      run: |
        cd NeuroML2
        python run_eden.py
        
    - name: Run OMV tests
      run: |
        pwd
        omv all -V
        
    - name: Print final OMV/engine version info
      run: |
        omv list -V # list installed engines
